name: eas preview build

on:
    workflow_run:
        workflows: [Node.js CI]
        types:
          - completed

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
        steps:
            - name: 🏗 Setup repo
              uses: actions/checkout@v3

            - name: 🏗 Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: npm

            - name: 🏗 Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: 📦 Install dependencies
              run: npm install

            - name: 🚀 Build android apk
              run: npm run build:ci:preview:android

            - name: 🚀 Build ios ipa
              run: npm run build:ci:preview:ios
